### ISSUE TITLE
Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by orzhtml** [reactnativecn/react-native-custom-keyboard#17]
报错

**Comment by NaNtrack** [comment]
+1

TypeError: Cannot read property 'install' of undefined

**Comment by Ash-faq** [comment]
can any one answer to this issue

**Comment by shivanitp** [comment]
Is anyone get the solution? 

I'm facing the same issue 

Test suite failed to run
TypeError: Cannot read property 'install' of undefined
      at Object.<anonymous> (node_modules/react-native/Libraries/ReactNative/AppContainer.js:153:12)
      at Object.<anonymous> (node_modules/react-native/Libraries/Modal/Modal.js:13:22)
